databases:
  - name: eduplay-db
    databaseName: eduplay
    user: eduplay
    plan: free

services:
  - type: web
    name: eduplay-backend
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: Dockerfile

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eduplay-db
          property: connectionString

      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: eduplay-db
          property: user

      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: eduplay-db
          property: password

      - key: APP_JWT_SECRET
        generateValue: true

      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: none

      - key: SPRING_SQL_INIT_MODE
        value: always

      - key: SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION
        value: "true"

      - key: SPRING_CACHE_TYPE
        value: none

      - key: SERVER_ADDRESS
        value: 0.0.0.0

    healthCheckPath: /api/health