spring.application.name=EduPlay
# Server
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/eduplay_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=TON_MOT_DE_PASSE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=86400000

# JWT
app.jwt.secret=EduPlay2024SuperSecretKeyPourJWTQuiDoitEtreLongue256bits!
app.jwt.expiration=86400000

# Anthropic API
anthropic.api.key=sk-ant-XXXXXXXXXXXXXXXX

# CORS
app.cors.allowed-origins=http://localhost:4200  