-- Script SQL EduPlay - Massive & Unique Dataset
BEGIN;
TRUNCATE TABLE question_bank;

INSERT INTO question_bank (question_text, choice_a, choice_b, choice_c, choice_d, correct_choice, explanation, subject, class_level, difficulty, topic_tag, quality_score, usage_count, app_language) VALUES 
('Calcule 1 + 9. (Série 1)', '20', '5', '15', '10', 'D', 'Le résultat de l''opération est 10.', 'MATH', 1, 'SIMPLE', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 4 + 8. (Série 1)', '(AR) 14', '(AR) 7', '(AR) 22', '(AR) 12', 'D', '(AR) Le résultat de l''opération est 12.', 'MATH', 1, 'SIMPLE', 'math', 95, 0, 'ARABIC'),
('Calcule 35 - 13. (Série 1)', '27', '32', '19', '22', 'D', 'Le résultat de l''opération est 22.', 'MATH', 1, 'MOYEN', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 39 - 8. (Série 1)', '(AR) 31', '(AR) 27', '(AR) 36', '(AR) 41', 'A', '(AR) Le résultat de l''opération est 31.', 'MATH', 1, 'MOYEN', 'math', 95, 0, 'ARABIC'),
('Calcule 8 x 8. (Série 1)', '67', '60', '64', '74', 'C', 'Le résultat de l''opération est 64.', 'MATH', 1, 'DIFFICILE', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 2 x 4. (Série 1)', '(AR) 9', '(AR) 8', '(AR) 18', '(AR) 3', 'B', '(AR) Le résultat de l''opération est 8.', 'MATH', 1, 'DIFFICILE', 'math', 95, 0, 'ARABIC'),
('Calcule 33 x 5. (Série 1)', '164', '165', '175', '169', 'B', 'Le résultat de l''opération est 165.', 'MATH', 1, 'EXCELLENT', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 37 x 5. (Série 1)', '(AR) 195', '(AR) 180', '(AR) 189', '(AR) 185', 'D', '(AR) Le résultat de l''opération est 185.', 'MATH', 1, 'EXCELLENT', 'math', 95, 0, 'ARABIC'),
('Calcule 9 + 5. (Série 1)', '14', '24', '9', '16', 'A', 'Le résultat de l''opération est 14.', 'MATH', 2, 'SIMPLE', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 7 + 3. (Série 1)', '(AR) 9', '(AR) 20', '(AR) 10', '(AR) 15', 'C', '(AR) Le résultat de l''opération est 10.', 'MATH', 2, 'SIMPLE', 'math', 95, 0, 'ARABIC'),
('Calcule 65 - 22. (Série 1)', '45', '53', '43', '40', 'C', 'Le résultat de l''opération est 43.', 'MATH', 2, 'MOYEN', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 75 - 21. (Série 1)', '(AR) 58', '(AR) 52', '(AR) 54', '(AR) 64', 'C', '(AR) Le résultat de l''opération est 54.', 'MATH', 2, 'MOYEN', 'math', 95, 0, 'ARABIC'),
('Calcule 2 x 8. (Série 1)', '12', '16', '26', '20', 'B', 'Le résultat de l''opération est 16.', 'MATH', 2, 'DIFFICILE', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 10 x 4. (Série 1)', '(AR) 40', '(AR) 50', '(AR) 37', '(AR) 42', 'A', '(AR) Le résultat de l''opération est 40.', 'MATH', 2, 'DIFFICILE', 'math', 95, 0, 'ARABIC'),
('Calcule 53 x 3. (Série 1)', '159', '155', '169', '160', 'A', 'Le résultat de l''opération est 159.', 'MATH', 2, 'EXCELLENT', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 103 x 3. (Série 1)', '(AR) 308', '(AR) 311', '(AR) 309', '(AR) 319', 'C', '(AR) Le résultat de l''opération est 309.', 'MATH', 2, 'EXCELLENT', 'math', 95, 0, 'ARABIC'),
('Calcule 22 + 29. (Série 1)', '49', '54', '61', '51', 'D', 'Le résultat de l''opération est 51.', 'MATH', 3, 'SIMPLE', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 7 + 27. (Série 1)', '(AR) 34', '(AR) 44', '(AR) 32', '(AR) 39', 'A', '(AR) Le résultat de l''opération est 34.', 'MATH', 3, 'SIMPLE', 'math', 95, 0, 'ARABIC'),
('Calcule 105 - 44. (Série 1)', '66', '71', '59', '61', 'D', 'Le résultat de l''opération est 61.', 'MATH', 3, 'MOYEN', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 104 - 10. (Série 1)', '(AR) 98', '(AR) 93', '(AR) 104', '(AR) 94', 'D', '(AR) Le résultat de l''opération est 94.', 'MATH', 3, 'MOYEN', 'math', 95, 0, 'ARABIC'),
('Calcule 2 x 6. (Série 1)', '12', '17', '8', '22', 'A', 'Le résultat de l''opération est 12.', 'MATH', 3, 'DIFFICILE', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 3 x 10. (Série 1)', '(AR) 40', '(AR) 30', '(AR) 33', '(AR) 27', 'B', '(AR) Le résultat de l''opération est 30.', 'MATH', 3, 'DIFFICILE', 'math', 95, 0, 'ARABIC'),
('Calcule 143 x 4. (Série 1)', '582', '575', '569', '572', 'D', 'Le résultat de l''opération est 572.', 'MATH', 3, 'EXCELLENT', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 148 x 4. (Série 1)', '(AR) 602', '(AR) 589', '(AR) 592', '(AR) 593', 'C', '(AR) Le résultat de l''opération est 592.', 'MATH', 3, 'EXCELLENT', 'math', 95, 0, 'ARABIC'),
('Calcule 27 + 26. (Série 1)', '63', '51', '53', '55', 'C', 'Le résultat de l''opération est 53.', 'MATH', 4, 'SIMPLE', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 40 + 6. (Série 1)', '(AR) 41', '(AR) 56', '(AR) 50', '(AR) 46', 'D', '(AR) Le résultat de l''opération est 46.', 'MATH', 4, 'SIMPLE', 'math', 95, 0, 'ARABIC'),
('Calcule 117 - 36. (Série 1)', '91', '81', '76', '86', 'B', 'Le résultat de l''opération est 81.', 'MATH', 4, 'MOYEN', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 100 - 19. (Série 1)', '(AR) 82', '(AR) 91', '(AR) 81', '(AR) 76', 'C', '(AR) Le résultat de l''opération est 81.', 'MATH', 4, 'MOYEN', 'math', 95, 0, 'ARABIC'),
('Calcule 8 x 10. (Série 1)', '77', '80', '82', '90', 'B', 'Le résultat de l''opération est 80.', 'MATH', 4, 'DIFFICILE', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 6 x 10. (Série 1)', '(AR) 70', '(AR) 64', '(AR) 56', '(AR) 60', 'D', '(AR) Le résultat de l''opération est 60.', 'MATH', 4, 'DIFFICILE', 'math', 95, 0, 'ARABIC'),
('Calcule 88 x 5. (Série 1)', '438', '445', '450', '440', 'D', 'Le résultat de l''opération est 440.', 'MATH', 4, 'EXCELLENT', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 154 x 2. (Série 1)', '(AR) 312', '(AR) 305', '(AR) 308', '(AR) 318', 'C', '(AR) Le résultat de l''opération est 308.', 'MATH', 4, 'EXCELLENT', 'math', 95, 0, 'ARABIC'),
('Calcule 6 + 41. (Série 1)', '47', '57', '43', '49', 'A', 'Le résultat de l''opération est 47.', 'MATH', 5, 'SIMPLE', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 34 + 7. (Série 1)', '(AR) 42', '(AR) 36', '(AR) 51', '(AR) 41', 'D', '(AR) Le résultat de l''opération est 41.', 'MATH', 5, 'SIMPLE', 'math', 95, 0, 'ARABIC'),
('Calcule 169 - 28. (Série 1)', '145', '151', '141', '140', 'C', 'Le résultat de l''opération est 141.', 'MATH', 5, 'MOYEN', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 150 - 29. (Série 1)', '(AR) 124', '(AR) 117', '(AR) 121', '(AR) 131', 'C', '(AR) Le résultat de l''opération est 121.', 'MATH', 5, 'MOYEN', 'math', 95, 0, 'ARABIC'),
('Calcule 2 x 4. (Série 1)', '4', '18', '8', '11', 'C', 'Le résultat de l''opération est 8.', 'MATH', 5, 'DIFFICILE', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 8 x 6. (Série 1)', '(AR) 48', '(AR) 53', '(AR) 58', '(AR) 46', 'A', '(AR) Le résultat de l''opération est 48.', 'MATH', 5, 'DIFFICILE', 'math', 95, 0, 'ARABIC'),
('Calcule 133 x 2. (Série 1)', '266', '263', '271', '276', 'A', 'Le résultat de l''opération est 266.', 'MATH', 5, 'EXCELLENT', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 186 x 4. (Série 1)', '(AR) 742', '(AR) 748', '(AR) 744', '(AR) 754', 'C', '(AR) Le résultat de l''opération est 744.', 'MATH', 5, 'EXCELLENT', 'math', 95, 0, 'ARABIC'),
('Calcule 56 + 50. (Série 1)', '102', '116', '109', '106', 'D', 'Le résultat de l''opération est 106.', 'MATH', 6, 'SIMPLE', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 34 + 44. (Série 1)', '(AR) 76', '(AR) 88', '(AR) 78', '(AR) 79', 'C', '(AR) Le résultat de l''opération est 78.', 'MATH', 6, 'SIMPLE', 'math', 95, 0, 'ARABIC'),
('Calcule 127 - 57. (Série 1)', '70', '80', '66', '74', 'A', 'Le résultat de l''opération est 70.', 'MATH', 6, 'MOYEN', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 231 - 94. (Série 1)', '(AR) 147', '(AR) 138', '(AR) 136', '(AR) 137', 'D', '(AR) Le résultat de l''opération est 137.', 'MATH', 6, 'MOYEN', 'math', 95, 0, 'ARABIC'),
('Calcule 9 x 2. (Série 1)', '18', '28', '23', '17', 'A', 'Le résultat de l''opération est 18.', 'MATH', 6, 'DIFFICILE', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 10 x 5. (Série 1)', '(AR) 60', '(AR) 55', '(AR) 50', '(AR) 48', 'C', '(AR) Le résultat de l''opération est 50.', 'MATH', 6, 'DIFFICILE', 'math', 95, 0, 'ARABIC'),
('Calcule 142 x 5. (Série 1)', '710', '715', '720', '708', 'A', 'Le résultat de l''opération est 710.', 'MATH', 6, 'EXCELLENT', 'math', 95, 0, 'FRENCH'),
('(AR) Calcule 245 x 5. (Série 1)', '(AR) 1235', '(AR) 1229', '(AR) 1224', '(AR) 1225', 'D', '(AR) Le résultat de l''opération est 1225.', 'MATH', 6, 'EXCELLENT', 'math', 95, 0, 'ARABIC'),
('Quel est le genre de ''le chat'' ?', 'masculin', 'féminin', 'neutre', 'aucun', 'A', 'On dit ''le chat'', c''est donc masculin.', 'FRENCH', 1, 'SIMPLE', 'french', 95, 0, 'FRENCH'),
('(AR) Quel est le genre de ''le chat'' ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) aucun', 'A', '(AR) On dit ''le chat'', c''est donc masculin.', 'FRENCH', 1, 'SIMPLE', 'french', 95, 0, 'ARABIC'),
('Quel est le genre de ''le chat'' ?', 'masculin', 'féminin', 'neutre', 'aucun', 'A', 'On dit ''le chat'', c''est donc masculin.', 'FRENCH', 1, 'MOYEN', 'french', 95, 0, 'FRENCH'),
('(AR) Quel est le genre de ''le chat'' ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) aucun', 'A', '(AR) On dit ''le chat'', c''est donc masculin.', 'FRENCH', 1, 'MOYEN', 'french', 95, 0, 'ARABIC'),
('Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', 'masculin', 'féminin', 'neutre', 'pluriel', 'A', 'Le mot ''le chat'' est de genre masculin.', 'FRENCH', 1, 'DIFFICILE', 'french', 95, 0, 'FRENCH'),
('(AR) Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) pluriel', 'A', '(AR) Le mot ''le chat'' est de genre masculin.', 'FRENCH', 1, 'DIFFICILE', 'french', 95, 0, 'ARABIC'),
('Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', 'masculin', 'féminin', 'neutre', 'pluriel', 'A', 'Le mot ''le chat'' est de genre masculin.', 'FRENCH', 1, 'EXCELLENT', 'french', 95, 0, 'FRENCH'),
('(AR) Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) pluriel', 'A', '(AR) Le mot ''le chat'' est de genre masculin.', 'FRENCH', 1, 'EXCELLENT', 'french', 95, 0, 'ARABIC'),
('Quel est le genre de ''le chat'' ?', 'masculin', 'féminin', 'neutre', 'aucun', 'A', 'On dit ''le chat'', c''est donc masculin.', 'FRENCH', 2, 'SIMPLE', 'french', 95, 0, 'FRENCH'),
('(AR) Quel est le genre de ''le chat'' ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) aucun', 'A', '(AR) On dit ''le chat'', c''est donc masculin.', 'FRENCH', 2, 'SIMPLE', 'french', 95, 0, 'ARABIC'),
('Quel est le genre de ''le chat'' ?', 'masculin', 'féminin', 'neutre', 'aucun', 'A', 'On dit ''le chat'', c''est donc masculin.', 'FRENCH', 2, 'MOYEN', 'french', 95, 0, 'FRENCH'),
('(AR) Quel est le genre de ''le chat'' ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) aucun', 'A', '(AR) On dit ''le chat'', c''est donc masculin.', 'FRENCH', 2, 'MOYEN', 'french', 95, 0, 'ARABIC'),
('Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', 'masculin', 'féminin', 'neutre', 'pluriel', 'A', 'Le mot ''le chat'' est de genre masculin.', 'FRENCH', 2, 'DIFFICILE', 'french', 95, 0, 'FRENCH'),
('(AR) Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) pluriel', 'A', '(AR) Le mot ''le chat'' est de genre masculin.', 'FRENCH', 2, 'DIFFICILE', 'french', 95, 0, 'ARABIC'),
('Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', 'masculin', 'féminin', 'neutre', 'pluriel', 'A', 'Le mot ''le chat'' est de genre masculin.', 'FRENCH', 2, 'EXCELLENT', 'french', 95, 0, 'FRENCH'),
('(AR) Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) pluriel', 'A', '(AR) Le mot ''le chat'' est de genre masculin.', 'FRENCH', 2, 'EXCELLENT', 'french', 95, 0, 'ARABIC'),
('Quel est le genre de ''le chat'' ?', 'masculin', 'féminin', 'neutre', 'aucun', 'A', 'On dit ''le chat'', c''est donc masculin.', 'FRENCH', 3, 'SIMPLE', 'french', 95, 0, 'FRENCH'),
('(AR) Quel est le genre de ''le chat'' ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) aucun', 'A', '(AR) On dit ''le chat'', c''est donc masculin.', 'FRENCH', 3, 'SIMPLE', 'french', 95, 0, 'ARABIC'),
('Quel est le genre de ''le chat'' ?', 'masculin', 'féminin', 'neutre', 'aucun', 'A', 'On dit ''le chat'', c''est donc masculin.', 'FRENCH', 3, 'MOYEN', 'french', 95, 0, 'FRENCH'),
('(AR) Quel est le genre de ''le chat'' ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) aucun', 'A', '(AR) On dit ''le chat'', c''est donc masculin.', 'FRENCH', 3, 'MOYEN', 'french', 95, 0, 'ARABIC'),
('Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', 'masculin', 'féminin', 'neutre', 'pluriel', 'A', 'Le mot ''le chat'' est de genre masculin.', 'FRENCH', 3, 'DIFFICILE', 'french', 95, 0, 'FRENCH'),
('(AR) Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) pluriel', 'A', '(AR) Le mot ''le chat'' est de genre masculin.', 'FRENCH', 3, 'DIFFICILE', 'french', 95, 0, 'ARABIC'),
('Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', 'masculin', 'féminin', 'neutre', 'pluriel', 'A', 'Le mot ''le chat'' est de genre masculin.', 'FRENCH', 3, 'EXCELLENT', 'french', 95, 0, 'FRENCH'),
('(AR) Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) pluriel', 'A', '(AR) Le mot ''le chat'' est de genre masculin.', 'FRENCH', 3, 'EXCELLENT', 'french', 95, 0, 'ARABIC'),
('Quel est le genre de ''le chat'' ?', 'masculin', 'féminin', 'neutre', 'aucun', 'A', 'On dit ''le chat'', c''est donc masculin.', 'FRENCH', 4, 'SIMPLE', 'french', 95, 0, 'FRENCH'),
('(AR) Quel est le genre de ''le chat'' ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) aucun', 'A', '(AR) On dit ''le chat'', c''est donc masculin.', 'FRENCH', 4, 'SIMPLE', 'french', 95, 0, 'ARABIC'),
('Quel est le genre de ''le chat'' ?', 'masculin', 'féminin', 'neutre', 'aucun', 'A', 'On dit ''le chat'', c''est donc masculin.', 'FRENCH', 4, 'MOYEN', 'french', 95, 0, 'FRENCH'),
('(AR) Quel est le genre de ''le chat'' ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) aucun', 'A', '(AR) On dit ''le chat'', c''est donc masculin.', 'FRENCH', 4, 'MOYEN', 'french', 95, 0, 'ARABIC'),
('Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', 'masculin', 'féminin', 'neutre', 'pluriel', 'A', 'Le mot ''le chat'' est de genre masculin.', 'FRENCH', 4, 'DIFFICILE', 'french', 95, 0, 'FRENCH'),
('(AR) Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) pluriel', 'A', '(AR) Le mot ''le chat'' est de genre masculin.', 'FRENCH', 4, 'DIFFICILE', 'french', 95, 0, 'ARABIC'),
('Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', 'masculin', 'féminin', 'neutre', 'pluriel', 'A', 'Le mot ''le chat'' est de genre masculin.', 'FRENCH', 4, 'EXCELLENT', 'french', 95, 0, 'FRENCH'),
('(AR) Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) pluriel', 'A', '(AR) Le mot ''le chat'' est de genre masculin.', 'FRENCH', 4, 'EXCELLENT', 'french', 95, 0, 'ARABIC'),
('Quel est le genre de ''le chat'' ?', 'masculin', 'féminin', 'neutre', 'aucun', 'A', 'On dit ''le chat'', c''est donc masculin.', 'FRENCH', 5, 'SIMPLE', 'french', 95, 0, 'FRENCH'),
('(AR) Quel est le genre de ''le chat'' ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) aucun', 'A', '(AR) On dit ''le chat'', c''est donc masculin.', 'FRENCH', 5, 'SIMPLE', 'french', 95, 0, 'ARABIC'),
('Quel est le genre de ''le chat'' ?', 'masculin', 'féminin', 'neutre', 'aucun', 'A', 'On dit ''le chat'', c''est donc masculin.', 'FRENCH', 5, 'MOYEN', 'french', 95, 0, 'FRENCH'),
('(AR) Quel est le genre de ''le chat'' ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) aucun', 'A', '(AR) On dit ''le chat'', c''est donc masculin.', 'FRENCH', 5, 'MOYEN', 'french', 95, 0, 'ARABIC'),
('Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', 'masculin', 'féminin', 'neutre', 'pluriel', 'A', 'Le mot ''le chat'' est de genre masculin.', 'FRENCH', 5, 'DIFFICILE', 'french', 95, 0, 'FRENCH'),
('(AR) Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) pluriel', 'A', '(AR) Le mot ''le chat'' est de genre masculin.', 'FRENCH', 5, 'DIFFICILE', 'french', 95, 0, 'ARABIC'),
('Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', 'masculin', 'féminin', 'neutre', 'pluriel', 'A', 'Le mot ''le chat'' est de genre masculin.', 'FRENCH', 5, 'EXCELLENT', 'french', 95, 0, 'FRENCH'),
('(AR) Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) pluriel', 'A', '(AR) Le mot ''le chat'' est de genre masculin.', 'FRENCH', 5, 'EXCELLENT', 'french', 95, 0, 'ARABIC'),
('Quel est le genre de ''le chat'' ?', 'masculin', 'féminin', 'neutre', 'aucun', 'A', 'On dit ''le chat'', c''est donc masculin.', 'FRENCH', 6, 'SIMPLE', 'french', 95, 0, 'FRENCH'),
('(AR) Quel est le genre de ''le chat'' ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) aucun', 'A', '(AR) On dit ''le chat'', c''est donc masculin.', 'FRENCH', 6, 'SIMPLE', 'french', 95, 0, 'ARABIC'),
('Quel est le genre de ''le chat'' ?', 'masculin', 'féminin', 'neutre', 'aucun', 'A', 'On dit ''le chat'', c''est donc masculin.', 'FRENCH', 6, 'MOYEN', 'french', 95, 0, 'FRENCH'),
('(AR) Quel est le genre de ''le chat'' ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) aucun', 'A', '(AR) On dit ''le chat'', c''est donc masculin.', 'FRENCH', 6, 'MOYEN', 'french', 95, 0, 'ARABIC'),
('Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', 'masculin', 'féminin', 'neutre', 'pluriel', 'A', 'Le mot ''le chat'' est de genre masculin.', 'FRENCH', 6, 'DIFFICILE', 'french', 95, 0, 'FRENCH'),
('(AR) Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) pluriel', 'A', '(AR) Le mot ''le chat'' est de genre masculin.', 'FRENCH', 6, 'DIFFICILE', 'french', 95, 0, 'ARABIC'),
('Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', 'masculin', 'féminin', 'neutre', 'pluriel', 'A', 'Le mot ''le chat'' est de genre masculin.', 'FRENCH', 6, 'EXCELLENT', 'french', 95, 0, 'FRENCH'),
('(AR) Dans la phrase ''L''enfant regarde le chat'', quel est le genre du complément ?', '(AR) masculin', '(AR) féminin', '(AR) neutre', '(AR) pluriel', 'A', '(AR) Le mot ''le chat'' est de genre masculin.', 'FRENCH', 6, 'EXCELLENT', 'french', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Mars', 'Vénus', 'Jupiter', 'Saturne', 'A', 'La réponse correcte est Mars.', 'SCIENCE', 1, 'SIMPLE', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Mars', '(AR) Saturne', '(AR) Vénus', '(AR) Jupiter', 'A', '(AR) La réponse correcte est Mars.', 'SCIENCE', 1, 'SIMPLE', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Saturne', 'Vénus', 'Jupiter', 'Mars', 'D', 'La réponse correcte est Mars.', 'SCIENCE', 1, 'MOYEN', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Saturne', '(AR) Mars', '(AR) Vénus', '(AR) Jupiter', 'B', '(AR) La réponse correcte est Mars.', 'SCIENCE', 1, 'MOYEN', 'science', 95, 0, 'ARABIC');
INSERT INTO question_bank (question_text, choice_a, choice_b, choice_c, choice_d, correct_choice, explanation, subject, class_level, difficulty, topic_tag, quality_score, usage_count, app_language) VALUES 
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Saturne', 'Jupiter', 'Vénus', 'Mars', 'D', 'La réponse correcte est Mars.', 'SCIENCE', 1, 'DIFFICILE', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Saturne', '(AR) Mars', '(AR) Jupiter', '(AR) Vénus', 'B', '(AR) La réponse correcte est Mars.', 'SCIENCE', 1, 'DIFFICILE', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Vénus', 'Saturne', 'Mars', 'Jupiter', 'C', 'La réponse correcte est Mars.', 'SCIENCE', 1, 'EXCELLENT', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Jupiter', '(AR) Saturne', '(AR) Mars', '(AR) Vénus', 'C', '(AR) La réponse correcte est Mars.', 'SCIENCE', 1, 'EXCELLENT', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Jupiter', 'Mars', 'Saturne', 'Vénus', 'B', 'La réponse correcte est Mars.', 'SCIENCE', 2, 'SIMPLE', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Mars', '(AR) Vénus', '(AR) Saturne', '(AR) Jupiter', 'A', '(AR) La réponse correcte est Mars.', 'SCIENCE', 2, 'SIMPLE', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Jupiter', 'Saturne', 'Mars', 'Vénus', 'C', 'La réponse correcte est Mars.', 'SCIENCE', 2, 'MOYEN', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Mars', '(AR) Vénus', '(AR) Saturne', '(AR) Jupiter', 'A', '(AR) La réponse correcte est Mars.', 'SCIENCE', 2, 'MOYEN', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Vénus', 'Mars', 'Saturne', 'Jupiter', 'B', 'La réponse correcte est Mars.', 'SCIENCE', 2, 'DIFFICILE', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Saturne', '(AR) Mars', '(AR) Jupiter', '(AR) Vénus', 'B', '(AR) La réponse correcte est Mars.', 'SCIENCE', 2, 'DIFFICILE', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Mars', 'Vénus', 'Jupiter', 'Saturne', 'A', 'La réponse correcte est Mars.', 'SCIENCE', 2, 'EXCELLENT', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Mars', '(AR) Vénus', '(AR) Saturne', '(AR) Jupiter', 'A', '(AR) La réponse correcte est Mars.', 'SCIENCE', 2, 'EXCELLENT', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Vénus', 'Mars', 'Jupiter', 'Saturne', 'B', 'La réponse correcte est Mars.', 'SCIENCE', 3, 'SIMPLE', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Jupiter', '(AR) Saturne', '(AR) Vénus', '(AR) Mars', 'D', '(AR) La réponse correcte est Mars.', 'SCIENCE', 3, 'SIMPLE', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Saturne', 'Vénus', 'Mars', 'Jupiter', 'C', 'La réponse correcte est Mars.', 'SCIENCE', 3, 'MOYEN', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Vénus', '(AR) Mars', '(AR) Jupiter', '(AR) Saturne', 'B', '(AR) La réponse correcte est Mars.', 'SCIENCE', 3, 'MOYEN', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Jupiter', 'Vénus', 'Saturne', 'Mars', 'D', 'La réponse correcte est Mars.', 'SCIENCE', 3, 'DIFFICILE', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Saturne', '(AR) Mars', '(AR) Vénus', '(AR) Jupiter', 'B', '(AR) La réponse correcte est Mars.', 'SCIENCE', 3, 'DIFFICILE', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Saturne', 'Jupiter', 'Vénus', 'Mars', 'D', 'La réponse correcte est Mars.', 'SCIENCE', 3, 'EXCELLENT', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Saturne', '(AR) Jupiter', '(AR) Mars', '(AR) Vénus', 'C', '(AR) La réponse correcte est Mars.', 'SCIENCE', 3, 'EXCELLENT', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Vénus', 'Saturne', 'Jupiter', 'Mars', 'D', 'La réponse correcte est Mars.', 'SCIENCE', 4, 'SIMPLE', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Vénus', '(AR) Mars', '(AR) Saturne', '(AR) Jupiter', 'B', '(AR) La réponse correcte est Mars.', 'SCIENCE', 4, 'SIMPLE', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Jupiter', 'Mars', 'Vénus', 'Saturne', 'B', 'La réponse correcte est Mars.', 'SCIENCE', 4, 'MOYEN', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Mars', '(AR) Vénus', '(AR) Jupiter', '(AR) Saturne', 'A', '(AR) La réponse correcte est Mars.', 'SCIENCE', 4, 'MOYEN', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Saturne', 'Jupiter', 'Vénus', 'Mars', 'D', 'La réponse correcte est Mars.', 'SCIENCE', 4, 'DIFFICILE', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Vénus', '(AR) Jupiter', '(AR) Mars', '(AR) Saturne', 'C', '(AR) La réponse correcte est Mars.', 'SCIENCE', 4, 'DIFFICILE', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Jupiter', 'Vénus', 'Mars', 'Saturne', 'C', 'La réponse correcte est Mars.', 'SCIENCE', 4, 'EXCELLENT', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Saturne', '(AR) Jupiter', '(AR) Mars', '(AR) Vénus', 'C', '(AR) La réponse correcte est Mars.', 'SCIENCE', 4, 'EXCELLENT', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Jupiter', 'Vénus', 'Mars', 'Saturne', 'C', 'La réponse correcte est Mars.', 'SCIENCE', 5, 'SIMPLE', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Saturne', '(AR) Jupiter', '(AR) Mars', '(AR) Vénus', 'C', '(AR) La réponse correcte est Mars.', 'SCIENCE', 5, 'SIMPLE', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Saturne', 'Jupiter', 'Vénus', 'Mars', 'D', 'La réponse correcte est Mars.', 'SCIENCE', 5, 'MOYEN', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Saturne', '(AR) Jupiter', '(AR) Mars', '(AR) Vénus', 'C', '(AR) La réponse correcte est Mars.', 'SCIENCE', 5, 'MOYEN', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Vénus', 'Jupiter', 'Saturne', 'Mars', 'D', 'La réponse correcte est Mars.', 'SCIENCE', 5, 'DIFFICILE', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Mars', '(AR) Vénus', '(AR) Saturne', '(AR) Jupiter', 'A', '(AR) La réponse correcte est Mars.', 'SCIENCE', 5, 'DIFFICILE', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Vénus', 'Saturne', 'Mars', 'Jupiter', 'C', 'La réponse correcte est Mars.', 'SCIENCE', 5, 'EXCELLENT', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Jupiter', '(AR) Vénus', '(AR) Saturne', '(AR) Mars', 'D', '(AR) La réponse correcte est Mars.', 'SCIENCE', 5, 'EXCELLENT', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Vénus', 'Saturne', 'Mars', 'Jupiter', 'C', 'La réponse correcte est Mars.', 'SCIENCE', 6, 'SIMPLE', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Mars', '(AR) Vénus', '(AR) Saturne', '(AR) Jupiter', 'A', '(AR) La réponse correcte est Mars.', 'SCIENCE', 6, 'SIMPLE', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Vénus', 'Mars', 'Saturne', 'Jupiter', 'B', 'La réponse correcte est Mars.', 'SCIENCE', 6, 'MOYEN', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Mars', '(AR) Saturne', '(AR) Vénus', '(AR) Jupiter', 'A', '(AR) La réponse correcte est Mars.', 'SCIENCE', 6, 'MOYEN', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Vénus', 'Mars', 'Jupiter', 'Saturne', 'B', 'La réponse correcte est Mars.', 'SCIENCE', 6, 'DIFFICILE', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Vénus', '(AR) Saturne', '(AR) Mars', '(AR) Jupiter', 'C', '(AR) La réponse correcte est Mars.', 'SCIENCE', 6, 'DIFFICILE', 'science', 95, 0, 'ARABIC'),
('Quelle planète est surnommée la planète rouge ? (Question 1)', 'Jupiter', 'Vénus', 'Mars', 'Saturne', 'C', 'La réponse correcte est Mars.', 'SCIENCE', 6, 'EXCELLENT', 'science', 95, 0, 'FRENCH'),
('(AR) Quelle planète est surnommée la planète rouge ? (Question 1)', '(AR) Jupiter', '(AR) Vénus', '(AR) Saturne', '(AR) Mars', 'D', '(AR) La réponse correcte est Mars.', 'SCIENCE', 6, 'EXCELLENT', 'science', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Magellan', 'Vasco de Gama', 'Marco Polo', 'Christophe Colomb', 'D', 'C''est Christophe Colomb.', 'HISTORY', 1, 'SIMPLE', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Vasco de Gama', '(AR) Magellan', '(AR) Christophe Colomb', '(AR) Marco Polo', 'C', '(AR) C''est Christophe Colomb.', 'HISTORY', 1, 'SIMPLE', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Marco Polo', 'Magellan', 'Christophe Colomb', 'Vasco de Gama', 'C', 'C''est Christophe Colomb.', 'HISTORY', 1, 'MOYEN', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Christophe Colomb', '(AR) Vasco de Gama', '(AR) Magellan', '(AR) Marco Polo', 'A', '(AR) C''est Christophe Colomb.', 'HISTORY', 1, 'MOYEN', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Vasco de Gama', 'Magellan', 'Christophe Colomb', 'Marco Polo', 'C', 'C''est Christophe Colomb.', 'HISTORY', 1, 'DIFFICILE', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Marco Polo', '(AR) Vasco de Gama', '(AR) Christophe Colomb', '(AR) Magellan', 'C', '(AR) C''est Christophe Colomb.', 'HISTORY', 1, 'DIFFICILE', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Magellan', 'Marco Polo', 'Christophe Colomb', 'Vasco de Gama', 'C', 'C''est Christophe Colomb.', 'HISTORY', 1, 'EXCELLENT', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Vasco de Gama', '(AR) Marco Polo', '(AR) Magellan', '(AR) Christophe Colomb', 'D', '(AR) C''est Christophe Colomb.', 'HISTORY', 1, 'EXCELLENT', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Magellan', 'Vasco de Gama', 'Christophe Colomb', 'Marco Polo', 'C', 'C''est Christophe Colomb.', 'HISTORY', 2, 'SIMPLE', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Vasco de Gama', '(AR) Marco Polo', '(AR) Magellan', '(AR) Christophe Colomb', 'D', '(AR) C''est Christophe Colomb.', 'HISTORY', 2, 'SIMPLE', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Magellan', 'Christophe Colomb', 'Vasco de Gama', 'Marco Polo', 'B', 'C''est Christophe Colomb.', 'HISTORY', 2, 'MOYEN', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Marco Polo', '(AR) Vasco de Gama', '(AR) Magellan', '(AR) Christophe Colomb', 'D', '(AR) C''est Christophe Colomb.', 'HISTORY', 2, 'MOYEN', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Magellan', 'Christophe Colomb', 'Vasco de Gama', 'Marco Polo', 'B', 'C''est Christophe Colomb.', 'HISTORY', 2, 'DIFFICILE', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Magellan', '(AR) Marco Polo', '(AR) Christophe Colomb', '(AR) Vasco de Gama', 'C', '(AR) C''est Christophe Colomb.', 'HISTORY', 2, 'DIFFICILE', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Magellan', 'Vasco de Gama', 'Christophe Colomb', 'Marco Polo', 'C', 'C''est Christophe Colomb.', 'HISTORY', 2, 'EXCELLENT', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Vasco de Gama', '(AR) Marco Polo', '(AR) Magellan', '(AR) Christophe Colomb', 'D', '(AR) C''est Christophe Colomb.', 'HISTORY', 2, 'EXCELLENT', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Marco Polo', 'Vasco de Gama', 'Magellan', 'Christophe Colomb', 'D', 'C''est Christophe Colomb.', 'HISTORY', 3, 'SIMPLE', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Magellan', '(AR) Vasco de Gama', '(AR) Marco Polo', '(AR) Christophe Colomb', 'D', '(AR) C''est Christophe Colomb.', 'HISTORY', 3, 'SIMPLE', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Christophe Colomb', 'Marco Polo', 'Magellan', 'Vasco de Gama', 'A', 'C''est Christophe Colomb.', 'HISTORY', 3, 'MOYEN', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Magellan', '(AR) Vasco de Gama', '(AR) Christophe Colomb', '(AR) Marco Polo', 'C', '(AR) C''est Christophe Colomb.', 'HISTORY', 3, 'MOYEN', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Marco Polo', 'Magellan', 'Christophe Colomb', 'Vasco de Gama', 'C', 'C''est Christophe Colomb.', 'HISTORY', 3, 'DIFFICILE', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Magellan', '(AR) Christophe Colomb', '(AR) Marco Polo', '(AR) Vasco de Gama', 'B', '(AR) C''est Christophe Colomb.', 'HISTORY', 3, 'DIFFICILE', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Vasco de Gama', 'Christophe Colomb', 'Magellan', 'Marco Polo', 'B', 'C''est Christophe Colomb.', 'HISTORY', 3, 'EXCELLENT', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Marco Polo', '(AR) Magellan', '(AR) Vasco de Gama', '(AR) Christophe Colomb', 'D', '(AR) C''est Christophe Colomb.', 'HISTORY', 3, 'EXCELLENT', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Marco Polo', 'Vasco de Gama', 'Christophe Colomb', 'Magellan', 'C', 'C''est Christophe Colomb.', 'HISTORY', 4, 'SIMPLE', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Vasco de Gama', '(AR) Christophe Colomb', '(AR) Marco Polo', '(AR) Magellan', 'B', '(AR) C''est Christophe Colomb.', 'HISTORY', 4, 'SIMPLE', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Marco Polo', 'Magellan', 'Christophe Colomb', 'Vasco de Gama', 'C', 'C''est Christophe Colomb.', 'HISTORY', 4, 'MOYEN', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Vasco de Gama', '(AR) Magellan', '(AR) Christophe Colomb', '(AR) Marco Polo', 'C', '(AR) C''est Christophe Colomb.', 'HISTORY', 4, 'MOYEN', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Magellan', 'Vasco de Gama', 'Marco Polo', 'Christophe Colomb', 'D', 'C''est Christophe Colomb.', 'HISTORY', 4, 'DIFFICILE', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Magellan', '(AR) Marco Polo', '(AR) Vasco de Gama', '(AR) Christophe Colomb', 'D', '(AR) C''est Christophe Colomb.', 'HISTORY', 4, 'DIFFICILE', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Vasco de Gama', 'Magellan', 'Christophe Colomb', 'Marco Polo', 'C', 'C''est Christophe Colomb.', 'HISTORY', 4, 'EXCELLENT', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Vasco de Gama', '(AR) Marco Polo', '(AR) Magellan', '(AR) Christophe Colomb', 'D', '(AR) C''est Christophe Colomb.', 'HISTORY', 4, 'EXCELLENT', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Christophe Colomb', 'Magellan', 'Marco Polo', 'Vasco de Gama', 'A', 'C''est Christophe Colomb.', 'HISTORY', 5, 'SIMPLE', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Marco Polo', '(AR) Vasco de Gama', '(AR) Magellan', '(AR) Christophe Colomb', 'D', '(AR) C''est Christophe Colomb.', 'HISTORY', 5, 'SIMPLE', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Vasco de Gama', 'Magellan', 'Christophe Colomb', 'Marco Polo', 'C', 'C''est Christophe Colomb.', 'HISTORY', 5, 'MOYEN', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Vasco de Gama', '(AR) Christophe Colomb', '(AR) Magellan', '(AR) Marco Polo', 'B', '(AR) C''est Christophe Colomb.', 'HISTORY', 5, 'MOYEN', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Vasco de Gama', 'Christophe Colomb', 'Magellan', 'Marco Polo', 'B', 'C''est Christophe Colomb.', 'HISTORY', 5, 'DIFFICILE', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Marco Polo', '(AR) Magellan', '(AR) Vasco de Gama', '(AR) Christophe Colomb', 'D', '(AR) C''est Christophe Colomb.', 'HISTORY', 5, 'DIFFICILE', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Magellan', 'Christophe Colomb', 'Vasco de Gama', 'Marco Polo', 'B', 'C''est Christophe Colomb.', 'HISTORY', 5, 'EXCELLENT', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Vasco de Gama', '(AR) Magellan', '(AR) Christophe Colomb', '(AR) Marco Polo', 'C', '(AR) C''est Christophe Colomb.', 'HISTORY', 5, 'EXCELLENT', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Christophe Colomb', 'Magellan', 'Marco Polo', 'Vasco de Gama', 'A', 'C''est Christophe Colomb.', 'HISTORY', 6, 'SIMPLE', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Magellan', '(AR) Christophe Colomb', '(AR) Marco Polo', '(AR) Vasco de Gama', 'B', '(AR) C''est Christophe Colomb.', 'HISTORY', 6, 'SIMPLE', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Marco Polo', 'Vasco de Gama', 'Christophe Colomb', 'Magellan', 'C', 'C''est Christophe Colomb.', 'HISTORY', 6, 'MOYEN', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Marco Polo', '(AR) Vasco de Gama', '(AR) Christophe Colomb', '(AR) Magellan', 'C', '(AR) C''est Christophe Colomb.', 'HISTORY', 6, 'MOYEN', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Christophe Colomb', 'Vasco de Gama', 'Marco Polo', 'Magellan', 'A', 'C''est Christophe Colomb.', 'HISTORY', 6, 'DIFFICILE', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Vasco de Gama', '(AR) Christophe Colomb', '(AR) Magellan', '(AR) Marco Polo', 'B', '(AR) C''est Christophe Colomb.', 'HISTORY', 6, 'DIFFICILE', 'history', 95, 0, 'ARABIC'),
('Qui a découvert l''Amérique en 1492 ? (Ref 1)', 'Magellan', 'Marco Polo', 'Vasco de Gama', 'Christophe Colomb', 'D', 'C''est Christophe Colomb.', 'HISTORY', 6, 'EXCELLENT', 'history', 95, 0, 'FRENCH'),
('(AR) Qui a découvert l''Amérique en 1492 ? (Ref 1)', '(AR) Vasco de Gama', '(AR) Magellan', '(AR) Marco Polo', '(AR) Christophe Colomb', 'D', '(AR) C''est Christophe Colomb.', 'HISTORY', 6, 'EXCELLENT', 'history', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Afrique', 'Asie', 'Europe', 'Amérique', 'B', 'La bonne réponse est Asie.', 'GEOGRAPHY', 1, 'SIMPLE', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Asie', '(AR) Afrique', '(AR) Europe', '(AR) Amérique', 'A', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 1, 'SIMPLE', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Afrique', 'Asie', 'Europe', 'Amérique', 'B', 'La bonne réponse est Asie.', 'GEOGRAPHY', 1, 'MOYEN', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Amérique', '(AR) Afrique', '(AR) Europe', '(AR) Asie', 'D', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 1, 'MOYEN', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Afrique', 'Asie', 'Europe', 'Amérique', 'B', 'La bonne réponse est Asie.', 'GEOGRAPHY', 1, 'DIFFICILE', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Afrique', '(AR) Amérique', '(AR) Europe', '(AR) Asie', 'D', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 1, 'DIFFICILE', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Amérique', 'Europe', 'Asie', 'Afrique', 'C', 'La bonne réponse est Asie.', 'GEOGRAPHY', 1, 'EXCELLENT', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Amérique', '(AR) Europe', '(AR) Asie', '(AR) Afrique', 'C', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 1, 'EXCELLENT', 'geography', 95, 0, 'ARABIC');
INSERT INTO question_bank (question_text, choice_a, choice_b, choice_c, choice_d, correct_choice, explanation, subject, class_level, difficulty, topic_tag, quality_score, usage_count, app_language) VALUES 
('Quel est le plus grand continent ? (Localisation 1)', 'Afrique', 'Amérique', 'Europe', 'Asie', 'D', 'La bonne réponse est Asie.', 'GEOGRAPHY', 2, 'SIMPLE', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Asie', '(AR) Europe', '(AR) Afrique', '(AR) Amérique', 'A', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 2, 'SIMPLE', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Asie', 'Europe', 'Amérique', 'Afrique', 'A', 'La bonne réponse est Asie.', 'GEOGRAPHY', 2, 'MOYEN', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Afrique', '(AR) Europe', '(AR) Asie', '(AR) Amérique', 'C', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 2, 'MOYEN', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Asie', 'Afrique', 'Amérique', 'Europe', 'A', 'La bonne réponse est Asie.', 'GEOGRAPHY', 2, 'DIFFICILE', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Afrique', '(AR) Amérique', '(AR) Asie', '(AR) Europe', 'C', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 2, 'DIFFICILE', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Asie', 'Europe', 'Amérique', 'Afrique', 'A', 'La bonne réponse est Asie.', 'GEOGRAPHY', 2, 'EXCELLENT', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Amérique', '(AR) Europe', '(AR) Afrique', '(AR) Asie', 'D', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 2, 'EXCELLENT', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Amérique', 'Asie', 'Afrique', 'Europe', 'B', 'La bonne réponse est Asie.', 'GEOGRAPHY', 3, 'SIMPLE', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Amérique', '(AR) Asie', '(AR) Afrique', '(AR) Europe', 'B', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 3, 'SIMPLE', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Amérique', 'Asie', 'Europe', 'Afrique', 'B', 'La bonne réponse est Asie.', 'GEOGRAPHY', 3, 'MOYEN', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Asie', '(AR) Afrique', '(AR) Amérique', '(AR) Europe', 'A', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 3, 'MOYEN', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Afrique', 'Asie', 'Europe', 'Amérique', 'B', 'La bonne réponse est Asie.', 'GEOGRAPHY', 3, 'DIFFICILE', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Europe', '(AR) Amérique', '(AR) Asie', '(AR) Afrique', 'C', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 3, 'DIFFICILE', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Afrique', 'Europe', 'Asie', 'Amérique', 'C', 'La bonne réponse est Asie.', 'GEOGRAPHY', 3, 'EXCELLENT', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Europe', '(AR) Amérique', '(AR) Afrique', '(AR) Asie', 'D', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 3, 'EXCELLENT', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Asie', 'Europe', 'Amérique', 'Afrique', 'A', 'La bonne réponse est Asie.', 'GEOGRAPHY', 4, 'SIMPLE', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Afrique', '(AR) Asie', '(AR) Europe', '(AR) Amérique', 'B', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 4, 'SIMPLE', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Asie', 'Amérique', 'Afrique', 'Europe', 'A', 'La bonne réponse est Asie.', 'GEOGRAPHY', 4, 'MOYEN', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Amérique', '(AR) Afrique', '(AR) Europe', '(AR) Asie', 'D', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 4, 'MOYEN', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Europe', 'Amérique', 'Asie', 'Afrique', 'C', 'La bonne réponse est Asie.', 'GEOGRAPHY', 4, 'DIFFICILE', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Asie', '(AR) Amérique', '(AR) Afrique', '(AR) Europe', 'A', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 4, 'DIFFICILE', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Asie', 'Amérique', 'Europe', 'Afrique', 'A', 'La bonne réponse est Asie.', 'GEOGRAPHY', 4, 'EXCELLENT', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Europe', '(AR) Asie', '(AR) Amérique', '(AR) Afrique', 'B', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 4, 'EXCELLENT', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Amérique', 'Asie', 'Afrique', 'Europe', 'B', 'La bonne réponse est Asie.', 'GEOGRAPHY', 5, 'SIMPLE', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Europe', '(AR) Asie', '(AR) Amérique', '(AR) Afrique', 'B', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 5, 'SIMPLE', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Afrique', 'Amérique', 'Europe', 'Asie', 'D', 'La bonne réponse est Asie.', 'GEOGRAPHY', 5, 'MOYEN', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Amérique', '(AR) Afrique', '(AR) Europe', '(AR) Asie', 'D', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 5, 'MOYEN', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Asie', 'Amérique', 'Europe', 'Afrique', 'A', 'La bonne réponse est Asie.', 'GEOGRAPHY', 5, 'DIFFICILE', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Afrique', '(AR) Europe', '(AR) Amérique', '(AR) Asie', 'D', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 5, 'DIFFICILE', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Europe', 'Asie', 'Amérique', 'Afrique', 'B', 'La bonne réponse est Asie.', 'GEOGRAPHY', 5, 'EXCELLENT', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Asie', '(AR) Europe', '(AR) Afrique', '(AR) Amérique', 'A', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 5, 'EXCELLENT', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Europe', 'Amérique', 'Asie', 'Afrique', 'C', 'La bonne réponse est Asie.', 'GEOGRAPHY', 6, 'SIMPLE', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Amérique', '(AR) Europe', '(AR) Asie', '(AR) Afrique', 'C', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 6, 'SIMPLE', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Europe', 'Afrique', 'Amérique', 'Asie', 'D', 'La bonne réponse est Asie.', 'GEOGRAPHY', 6, 'MOYEN', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Afrique', '(AR) Europe', '(AR) Amérique', '(AR) Asie', 'D', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 6, 'MOYEN', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Afrique', 'Amérique', 'Asie', 'Europe', 'C', 'La bonne réponse est Asie.', 'GEOGRAPHY', 6, 'DIFFICILE', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Amérique', '(AR) Europe', '(AR) Afrique', '(AR) Asie', 'D', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 6, 'DIFFICILE', 'geography', 95, 0, 'ARABIC'),
('Quel est le plus grand continent ? (Localisation 1)', 'Afrique', 'Amérique', 'Asie', 'Europe', 'C', 'La bonne réponse est Asie.', 'GEOGRAPHY', 6, 'EXCELLENT', 'geography', 95, 0, 'FRENCH'),
('(AR) Quel est le plus grand continent ? (Localisation 1)', '(AR) Afrique', '(AR) Asie', '(AR) Europe', '(AR) Amérique', 'B', '(AR) La bonne réponse est Asie.', 'GEOGRAPHY', 6, 'EXCELLENT', 'geography', 95, 0, 'ARABIC'),
('ماذا يسمى صغير الأسد؟', 'حمل', 'شبل', 'هر', 'جرو', 'B', 'الشبل هو صغير الأسد.', 'ARABIC', 1, 'SIMPLE', 'arabic', 95, 0, 'FRENCH'),
('ماذا يسمى صغير الأسد؟', 'هر', 'حمل', 'شبل', 'جرو', 'C', 'الشبل هو صغير الأسد.', 'ARABIC', 1, 'SIMPLE', 'arabic', 95, 0, 'ARABIC'),
('ما هو الفاعل في جملة ''قرأ التلميذُ القصةَ''؟', 'القصةَ', 'التلميذُ', 'مستتر', 'قرأ', 'B', 'الفاعل هو من قام بالفعل ويكون مرفوعاً.', 'ARABIC', 1, 'MOYEN', 'arabic', 95, 0, 'FRENCH'),
('ما هو الفاعل في جملة ''قرأ التلميذُ القصةَ''؟', 'التلميذُ', 'القصةَ', 'قرأ', 'مستتر', 'A', 'الفاعل هو من قام بالفعل ويكون مرفوعاً.', 'ARABIC', 1, 'MOYEN', 'arabic', 95, 0, 'ARABIC'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'خبر', 'مفعول به', 'فاعل', 'مبتدأ', 'D', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 1, 'DIFFICILE', 'arabic', 95, 0, 'FRENCH'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مبتدأ', 'خبر', 'فاعل', 'مفعول به', 'A', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 1, 'DIFFICILE', 'arabic', 95, 0, 'ARABIC'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مفعول به', 'مبتدأ', 'فاعل', 'خبر', 'B', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 1, 'EXCELLENT', 'arabic', 95, 0, 'FRENCH'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مبتدأ', 'خبر', 'فاعل', 'مفعول به', 'A', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 1, 'EXCELLENT', 'arabic', 95, 0, 'ARABIC'),
('ماذا يسمى صغير الأسد؟', 'جرو', 'حمل', 'شبل', 'هر', 'C', 'الشبل هو صغير الأسد.', 'ARABIC', 2, 'SIMPLE', 'arabic', 95, 0, 'FRENCH'),
('ماذا يسمى صغير الأسد؟', 'حمل', 'شبل', 'هر', 'جرو', 'B', 'الشبل هو صغير الأسد.', 'ARABIC', 2, 'SIMPLE', 'arabic', 95, 0, 'ARABIC'),
('ما هو الفاعل في جملة ''قرأ التلميذُ القصةَ''؟', 'مستتر', 'القصةَ', 'التلميذُ', 'قرأ', 'C', 'الفاعل هو من قام بالفعل ويكون مرفوعاً.', 'ARABIC', 2, 'MOYEN', 'arabic', 95, 0, 'FRENCH'),
('ما هو الفاعل في جملة ''قرأ التلميذُ القصةَ''؟', 'مستتر', 'التلميذُ', 'القصةَ', 'قرأ', 'B', 'الفاعل هو من قام بالفعل ويكون مرفوعاً.', 'ARABIC', 2, 'MOYEN', 'arabic', 95, 0, 'ARABIC'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'خبر', 'مبتدأ', 'مفعول به', 'فاعل', 'B', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 2, 'DIFFICILE', 'arabic', 95, 0, 'FRENCH'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'خبر', 'مبتدأ', 'مفعول به', 'فاعل', 'B', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 2, 'DIFFICILE', 'arabic', 95, 0, 'ARABIC'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مفعول به', 'مبتدأ', 'فاعل', 'خبر', 'B', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 2, 'EXCELLENT', 'arabic', 95, 0, 'FRENCH'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مفعول به', 'خبر', 'فاعل', 'مبتدأ', 'D', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 2, 'EXCELLENT', 'arabic', 95, 0, 'ARABIC'),
('ماذا يسمى صغير الأسد؟', 'هر', 'شبل', 'جرو', 'حمل', 'B', 'الشبل هو صغير الأسد.', 'ARABIC', 3, 'SIMPLE', 'arabic', 95, 0, 'FRENCH'),
('ماذا يسمى صغير الأسد؟', 'شبل', 'هر', 'جرو', 'حمل', 'A', 'الشبل هو صغير الأسد.', 'ARABIC', 3, 'SIMPLE', 'arabic', 95, 0, 'ARABIC'),
('ما هو الفاعل في جملة ''قرأ التلميذُ القصةَ''؟', 'القصةَ', 'قرأ', 'مستتر', 'التلميذُ', 'D', 'الفاعل هو من قام بالفعل ويكون مرفوعاً.', 'ARABIC', 3, 'MOYEN', 'arabic', 95, 0, 'FRENCH'),
('ما هو الفاعل في جملة ''قرأ التلميذُ القصةَ''؟', 'مستتر', 'قرأ', 'القصةَ', 'التلميذُ', 'D', 'الفاعل هو من قام بالفعل ويكون مرفوعاً.', 'ARABIC', 3, 'MOYEN', 'arabic', 95, 0, 'ARABIC'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'خبر', 'مفعول به', 'مبتدأ', 'فاعل', 'C', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 3, 'DIFFICILE', 'arabic', 95, 0, 'FRENCH'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مبتدأ', 'فاعل', 'خبر', 'مفعول به', 'A', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 3, 'DIFFICILE', 'arabic', 95, 0, 'ARABIC'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مفعول به', 'خبر', 'مبتدأ', 'فاعل', 'C', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 3, 'EXCELLENT', 'arabic', 95, 0, 'FRENCH'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مفعول به', 'فاعل', 'خبر', 'مبتدأ', 'D', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 3, 'EXCELLENT', 'arabic', 95, 0, 'ARABIC'),
('ماذا يسمى صغير الأسد؟', 'جرو', 'هر', 'شبل', 'حمل', 'C', 'الشبل هو صغير الأسد.', 'ARABIC', 4, 'SIMPLE', 'arabic', 95, 0, 'FRENCH'),
('ماذا يسمى صغير الأسد؟', 'حمل', 'جرو', 'شبل', 'هر', 'C', 'الشبل هو صغير الأسد.', 'ARABIC', 4, 'SIMPLE', 'arabic', 95, 0, 'ARABIC'),
('ما هو الفاعل في جملة ''قرأ التلميذُ القصةَ''؟', 'قرأ', 'مستتر', 'التلميذُ', 'القصةَ', 'C', 'الفاعل هو من قام بالفعل ويكون مرفوعاً.', 'ARABIC', 4, 'MOYEN', 'arabic', 95, 0, 'FRENCH'),
('ما هو الفاعل في جملة ''قرأ التلميذُ القصةَ''؟', 'التلميذُ', 'قرأ', 'القصةَ', 'مستتر', 'A', 'الفاعل هو من قام بالفعل ويكون مرفوعاً.', 'ARABIC', 4, 'MOYEN', 'arabic', 95, 0, 'ARABIC'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مبتدأ', 'مفعول به', 'فاعل', 'خبر', 'A', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 4, 'DIFFICILE', 'arabic', 95, 0, 'FRENCH'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مبتدأ', 'خبر', 'مفعول به', 'فاعل', 'A', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 4, 'DIFFICILE', 'arabic', 95, 0, 'ARABIC'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مبتدأ', 'خبر', 'فاعل', 'مفعول به', 'A', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 4, 'EXCELLENT', 'arabic', 95, 0, 'FRENCH'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'فاعل', 'مفعول به', 'خبر', 'مبتدأ', 'D', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 4, 'EXCELLENT', 'arabic', 95, 0, 'ARABIC'),
('ماذا يسمى صغير الأسد؟', 'شبل', 'هر', 'حمل', 'جرو', 'A', 'الشبل هو صغير الأسد.', 'ARABIC', 5, 'SIMPLE', 'arabic', 95, 0, 'FRENCH'),
('ماذا يسمى صغير الأسد؟', 'حمل', 'هر', 'شبل', 'جرو', 'C', 'الشبل هو صغير الأسد.', 'ARABIC', 5, 'SIMPLE', 'arabic', 95, 0, 'ARABIC'),
('ما هو الفاعل في جملة ''قرأ التلميذُ القصةَ''؟', 'القصةَ', 'قرأ', 'التلميذُ', 'مستتر', 'C', 'الفاعل هو من قام بالفعل ويكون مرفوعاً.', 'ARABIC', 5, 'MOYEN', 'arabic', 95, 0, 'FRENCH'),
('ما هو الفاعل في جملة ''قرأ التلميذُ القصةَ''؟', 'قرأ', 'مستتر', 'القصةَ', 'التلميذُ', 'D', 'الفاعل هو من قام بالفعل ويكون مرفوعاً.', 'ARABIC', 5, 'MOYEN', 'arabic', 95, 0, 'ARABIC'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مبتدأ', 'مفعول به', 'فاعل', 'خبر', 'A', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 5, 'DIFFICILE', 'arabic', 95, 0, 'FRENCH'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'خبر', 'مفعول به', 'مبتدأ', 'فاعل', 'C', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 5, 'DIFFICILE', 'arabic', 95, 0, 'ARABIC'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'فاعل', 'مبتدأ', 'مفعول به', 'خبر', 'B', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 5, 'EXCELLENT', 'arabic', 95, 0, 'FRENCH'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مفعول به', 'خبر', 'مبتدأ', 'فاعل', 'C', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 5, 'EXCELLENT', 'arabic', 95, 0, 'ARABIC'),
('ماذا يسمى صغير الأسد؟', 'حمل', 'هر', 'جرو', 'شبل', 'D', 'الشبل هو صغير الأسد.', 'ARABIC', 6, 'SIMPLE', 'arabic', 95, 0, 'FRENCH'),
('ماذا يسمى صغير الأسد؟', 'حمل', 'شبل', 'جرو', 'هر', 'B', 'الشبل هو صغير الأسد.', 'ARABIC', 6, 'SIMPLE', 'arabic', 95, 0, 'ARABIC'),
('ما هو الفاعل في جملة ''قرأ التلميذُ القصةَ''؟', 'قرأ', 'التلميذُ', 'مستتر', 'القصةَ', 'B', 'الفاعل هو من قام بالفعل ويكون مرفوعاً.', 'ARABIC', 6, 'MOYEN', 'arabic', 95, 0, 'FRENCH'),
('ما هو الفاعل في جملة ''قرأ التلميذُ القصةَ''؟', 'مستتر', 'قرأ', 'التلميذُ', 'القصةَ', 'C', 'الفاعل هو من قام بالفعل ويكون مرفوعاً.', 'ARABIC', 6, 'MOYEN', 'arabic', 95, 0, 'ARABIC'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'خبر', 'مفعول به', 'فاعل', 'مبتدأ', 'D', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 6, 'DIFFICILE', 'arabic', 95, 0, 'FRENCH'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'فاعل', 'خبر', 'مبتدأ', 'مفعول به', 'C', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 6, 'DIFFICILE', 'arabic', 95, 0, 'ARABIC'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مفعول به', 'خبر', 'مبتدأ', 'فاعل', 'C', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 6, 'EXCELLENT', 'arabic', 95, 0, 'FRENCH'),
('ما هو إعراب ''الجوُّ'' في جملة ''الجوُّ جميلٌ''؟', 'مفعول به', 'خبر', 'مبتدأ', 'فاعل', 'C', 'الاسم في بداية الجملة الاسمية يعرب مبتدأ.', 'ARABIC', 6, 'EXCELLENT', 'arabic', 95, 0, 'ARABIC');

COMMIT;
